apiVersion: v1
clusters:
  - cluster:
      server: 'https://53BBC1E3E1EAE409F752C3896DE3CAD3.yl4.eu-west-1.eks.amazonaws.com'
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1UQXpNREU0TURnMU4xb1hEVEk1TVRBeU56RTRNRGcxTjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS2lSCnZFZnZlSFh1QzhwYnlENzYwd2tNWEg2SnhoaGlCelhyTC9rL0h0VEdCenJ4dkNXT1FsWnVVNDBrT2xsTkthTlEKZ3oweG5EUjkzKzd4cmRmeWdTSjdxYWpSYW5NazFxZ1lNc0Z2blBWNmZjdWxNWDNmemdQMG96VEZHWjRoc1Z6aAovZFM0bGpnMnRiTG4vbGRsY0w3eWpKbS9UZ1p1bGtxVjhIUHNrMGpsZUo2ajhTZWtBcmJNVGw1SEdaWmJSNDU1CkVTdEJDWUZQMkxMZUQ1M1dlVGJ1M1hJTGNEQzR6WTd2MWxWcEJGOTRPNHlDeHpjdjA0Y0hMc3JPOHQ1YXNUcTQKUi9DRXg3RVdwT2RjbXVZR2dsU1BDZTcyUmhQWXhPaDg1U1Q3Mm05TnRNQ1RVTzZoQmlkOGF1ZU5PU1hFTmJ0NwpIK2VXNEtpTnhTd2lhY0Qrc3NFQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJbnhKQkZnMWVWeFhnNXN4MXJzWkNUZjFWMXUKczRHMEFHenBpK0pOMzRpR2JLbElwOXJJWmdWNjZyMGRnVzl4VC9VOHU1ZVJ1Vk9oNHpxcXkyYS84N0docjZDNQoxdTdKRXNFL2d0cG9CMThBQmpobEI5blBkMTkvM3B3dGFhTVRwcWMrTkJraC9lc2htVXlNUEE2V2pCN0FicW5jCndIUWYvSnNoZklJdENUVnpjUllOUUlDMkdJQ1VpemVXTFpIcllmemIwZTNtempvWDdEbkJnbUh3akVJVllyRmUKQlFOZVJNKzJsV0FadnJrTE9BK2hqdWRnbVJTeGZ2SnU0TFpwVHY5Q0dOSElZczJLMTZqSXpZOFdwdVI1ODRjNQpIOW52REhvdXdoczlrSzN4VjlyYjAvTUNyazRZSWxXWDFzSnBNU3N2Y3ZaZnB6cVJyWDNhbS9SUHc0VT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    name: kubernetes
contexts:
  - context:
      cluster: kubernetes
      user: aws
    name: aws
current-context: aws
kind: Config
users:
  - name: aws
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        command: aws-iam-authenticator
        args:
          - token
          - '-i'
          - gen1-stable-eksCluster-415be5f

