version: 2
jobs:
  build_and_test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:11.6.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - reqres-yarn-{{ checksum "yarn.lock" }}
            - reqres-yarn-
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: reqres-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/repo/node_modules
      - run:
          name: Javascript tests
          command: yarn test --exit

  build_docker:
    working_directory: ~/repo
    docker:
      - image: 312707417434.dkr.ecr.us-east-1.amazonaws.com/xapixio/docker-kops-helm:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          type: shell
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            echo "$CIRCLE_SHA1" > REVISION
            docker build -t xapixio/reqres:$CIRCLE_SHA1 -t xapixio/reqres:develop .
            docker push xapixio/reqres:$CIRCLE_SHA1
            docker push xapixio/reqres:develop

workflows:
  version: 2
  build:
    jobs:
      - build_and_test
      - build_docker:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
