# TODO: switch to private @actions/docker when actions sharing will be available
name: CD
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
    - name: Revision
      run: echo "${{ github.sha }}" > REVISION
    - name: Install deps
      run: yarn install
    - name: Run tests
      run: yarn test --exit
    - name: Build docker
      run: |
        REPO=xapixio/reqres
        IMAGE=$REPO:$GITHUB_SHA
        DEVELOP_IMAGE=$REPO:develop
        docker login -u xapixbot -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker build -t $IMAGE -t $DEVELOP_IMAGE .
        docker push $IMAGE
        if [ "$GITHUB_REF" = "refs/heads/master" ] ; then docker push $DEVELOP_IMAGE ; fi

  deploy:
    runs-on: ubuntu-latest
    if: "'refs/heads/master' == github.ref"
    needs: [build]
    strategy:
      matrix:
        fail-fast: false
        stack: [dev, stable]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: prepor/action-aws-iam-authenticator@master
      - uses: prepor/setup-pulumi@master
        with:
          version: 1.4.1
      - run: echo "//npm.pkg.github.com/:_authToken=${{secrets.XAPIX_GITHUB_TOKEN}}" >> .npmrc
        working-directory: ./infra
      - uses: prepor/github-pulumi@master
        with:
          stack: xapix/${{ matrix.stack }}
          args: up
          root: infra
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          VERSION: ${{ github.sha }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  configs:
    runs-on: ubuntu-latest
    if: "'refs/heads/master' == github.ref"
    steps:
      - uses: actions/checkout@v1
      - name: Config Docs
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{secrets.XAPIX_GITHUB_TOKEN}}" >> .npmrc
          npm install
          npm run build
          npm run docs-config
        working-directory: ./infra
      - name: Upload Docs to Wiki
        uses: docker://decathlon/wiki-page-creator-action:latest
        env:
          # FIXME we should setup other email for xapixbot user and start using it here
          ACTION_MAIL: andrey@xapix.io
          ACTION_NAME: xapixbot
          GH_PAT: ${{ secrets.XAPIX_GITHUB_TOKEN }}
          MD_FOLDER: infra/docs
          OWNER: xapix-io
          REPO_NAME: reqres
